name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_branch: "repo-visualizer"
          commit_message: "Update repository visualization"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: repo-visualizer
