name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "ignore,.github"
          output_file: "diagram.svg"

      - name: Create and push branch with only diagram
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          timestamp=$(date +"%Y%m%d_%H%M%S")
          
          # Copy the diagram files to a temporary location
          cp diagram.svg /tmp/diagram.svg
          cp diagram.svg "/tmp/diagram_${timestamp}.svg"
          
          # Create a new orphan branch
          git checkout --orphan repo-visualizer
          
          # Remove all files from the working directory
          git rm -rf .
          
          # Move the diagram files from the temporary location
          mv /tmp/diagram.svg .
          mv "/tmp/diagram_${timestamp}.svg" .
          
          # Add and commit only the diagram files
          git add diagram.svg "diagram_${timestamp}.svg"
          git commit -m "Update repository visualization - $timestamp"
          
          # Force push to the repo-visualizer branch
          git push origin repo-visualizer --force
