name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "ignore,.github"
          output_file: "diagram.svg"

      - name: Create and push branch with timestamped diagram
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          timestamp=$(date +"%Y%m%d_%H%M%S")
          mv diagram.svg "diagram_${timestamp}.svg"
          git checkout --orphan repo-visualizer
          git rm -rf .
          git add "diagram_${timestamp}.svg"
          git commit -m "Update repository visualization - $timestamp"
          git push origin repo-visualizer --force
