name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "ignore,.github"
          output_file: "diagram.svg"
          branch: "repo-visualizer"
          commit_message: "Update repository visualization"

      - name: Add timestamped copy
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
          
          # Checkout the repo-visualizer branch
          git fetch origin repo-visualizer
          git checkout repo-visualizer
          
          # Create a timestamped copy
          cp diagram.svg "diagram_${timestamp}.svg"
          
          # Add and commit the timestamped copy
          git add "diagram_${timestamp}.svg"
          git commit -m "Add timestamped diagram - ${timestamp}"
          
          # Push changes
          git push origin repo-visualizer
